_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: es
uuid: 1f6bdda9-bf94-40a5-8718-4c665d9db8ab
name: Lab2
mail: rakel.2695@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: es
